### ISSUE TITLE
Window10 System open exe error,Dialog show missing VCRUNTIME140_1.dll

### ISSUE THREAD

**Issue by panyiho** [gskinnerTeam/flokk#15]
Window10 System open exe error,Dialog show missing VCRUNTIME140_1.dll

**Comment by kuanhulio** [comment]
@panyiho 

You need to install the VS C++ Redist 2015 pack. It's on MS's site.

**Comment by trevordunn** [comment]
This one? https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by kuanhulio** [comment]
@trevordunn I was personally linked [this](https://www.microsoft.com/en-us/download/details.aspx?id=52685) but your link will probably work as well.

**Comment by trevordunn** [comment]
Updated the readme and releases with a note about this.

@panyiho if you're still having trouble after installing the VS C++ Redis 2015 pack, feel free to comment with more details and we can reopen.

**Comment by stuartmorgan** [comment]
FYI: https://github.com/flutter/flutter/wiki/Desktop-shells#distributing

The prebuilt version should really be using one of those solutions, rather than relying on users to install the libraries manually.

**Comment by kuanhulio** [comment]
> Keep in mind that the Windows embedding is in early stages, and is missing critical functionality such as OS accessibility integration, so we **strongly recommend against distributing applications to end users** at this stage.

Looks to me that Flutter isn't exactly ready for that part yet, if I am reading that right?

**Comment by stuartmorgan** [comment]
That warning has nothing to do with this issue; "Should desktop Flutter applications be considered production-ready and distributed to and users?" and "How should a Windows program that depends on the VS C++ redistributables be distributed?"  are completely orthogonal questions. The warning you quoted is about the former, and this issue is about the latter.

**Comment by kuanhulio** [comment]
@stuartmorgan 

Currently, I don't see why those are separate. Yes, we should be packing them in, but Flutter is still under active development in the Windows sector, so until there's a platform stability update that won't change the API, then we shouldn't really need to worry about it. 

However, you can go ahead and make a PR fixing it, I just don't think we should fully fix it considering it might be fixed in a stable version of flutter, since we are on the bleeding edge here.

**Comment by esDotDev** [comment]
> That warning has nothing to do with this issue; "Should desktop Flutter applications be considered production-ready and distributed to and users?" and "How should a Windows program that depends on the VS C++ redistributables be distributed?" are completely orthogonal questions. The warning you quoted is about the former, and this issue is about the latter.

Thanks for the note, will do

**Comment by stuartmorgan** [comment]
> until there's a platform stability update that won't change the API, then we shouldn't really need to worry about it

API changes are built-time issues, not runtime. The fact that APIs may change means that your `windows` directory and your plugin version pins may both periodically be broken (as is, in fact, the case with the current master); it doesn't affect the runtime dependencies. So I don't see how this follows at all.

The application will still be a C++ Windows application, and thus still have these basic runtime dependencies, when the APIs are stable.
